version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - ./database/data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-ui
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_URL=
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    ports:
      - 8081:8081
    networks:
      - backend
    links:
      - mongo:mongo
    depends_on:
      - mongo

  server:
    image: ghcr.io/dmytro-komlyk/prod-fixlab-server:latest
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env.example
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_DB_LINK=
      - MONGO_DB_NAME=
      - MONGO_DB_AUTH_USERNAME=
      - MONGO_DB_AUTH_PASSWORD=
      - SECRET=
      - D_ADMIN_KEY=
    ports:
      - 30000:3000
    networks:
      - frontend
      - backend
    depends_on:
      - mongo
    links:
      - mongo

  client:
    image: ghcr.io/dmytro-komlyk/prod-fixlab-client:latest
    container_name: client
    restart: unless-stopped
    env_file: ./client/.env.example
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SERVER_API_KEY=
    ports:
      - "30001:3001"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  database:
    driver: local
